version: '3.5'

services:

  postgresql:
    image: 'postgres:15-alpine'
    container_name: postgresql
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scrapper
    restart: always
    networks:
      - backend

volumes:
  postgres-data:
    name: postgres-data

networks:
  backend: { }
